area:frontend:
  - changed-files:
      - any-glob-to-any-file: 'frontend/**'

area:backend:
  - changed-files:
      - any-glob-to-any-file: 'backend/**'

area:ci:
  - changed-files:
      - any-glob-to-any-file: '.github/**'

area:docs:
  - changed-files:
      - any-glob-to-any-file: '**/*.md'

type:config:
  - changed-files:
      - any-glob-to-any-file: '**/*.{json,yml,yaml}'

